name: KB Health Check

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
  # Also run after KB builds complete
  workflow_run:
    workflows: ["Rebuild KB and Enforce Embedding Coverage"]
    types:
      - completed

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Run health check
        env:
          SITE_URL: https://ai.olivogalarza.com
          ALERT_WEBHOOK_URL: ${{ secrets.ALERT_WEBHOOK_URL }}
        run: node scripts/monitor-kb-health.js

      - name: Report status
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Health check passed"
          else
            echo "❌ Health check failed"
            exit 1
          fi
